# Q1.	Import the attached Netflix csv file in Jupyter notebook and perform following operations using Pandas:

In [182]:
import pandas as pd
import numpy as np

In [183]:
!ls

 Marks.xlsm   sample_data   Student.xlsm   test.csv  'Worksheet in Assignment.xlsm'

In [184]:
Netflix_data=pd.read_excel("/content/Worksheet in Assignment.xlsm")
print(Netflix_data.head())

  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season
3  September 24, 2021          2021  TV-MA   1 Season
4  September 24, 2021          2021  TV-MA  2 Seasons

                                           listed_in
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

In [185]:
# a)	Print the first 5 rows and last 5 rows of the dataframe

Top_five_rows=Netflix_data.head()
Last_Five_rows=Netflix_data.tail()
print(Top_five_rows)
print(Last_Five_rows)

  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season
3  September 24, 2021          2021  TV-MA   1 Season
4  September 24, 2021          2021  TV-MA  2 Seasons

                                           listed_in
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...
     show_id     type        title         director  \
8775   s8803    Movie       Zodiac    David Fincher
8776   s8804  TV Show  Zombie Dumb              NaN
8777   s8805    Movie   Zombieland  Ruben Fleischer
8778   s8806    Movie         Zoom     Peter Hewitt
8779   s8807    Movie       Zubaan      Mozez Singh

                                                   cast        country  \
8775  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8776                                                NaN            NaN
8777  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8778  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8779  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

             date_added  release_year rating   duration  \
8775  November 20, 2019          2007      R    158 min
8776       July 1, 2019          2018  TV-Y7  2 Seasons
8777   November 1, 2019          2009      R     88 min
8778   January 11, 2020          2006     PG     88 min
8779      March 2, 2019          2015  TV-14    111 min

                                           listed_in
8775                  Cult Movies, Dramas, Thrillers
8776          Kids' TV, Korean TV Shows, TV Comedies
8777                         Comedies, Horror Movies
8778              Children & Family Movies, Comedies
8779  Dramas, International Movies, Music & Musicals

In [186]:
#b)	Check how many rows and columns are there using Pandas function

Number_of_rows_columns=Netflix_data.shape
Number_of_rows_columns

(8780, 11)

In [187]:
#c)	Print all the column names.

Column_Name=Netflix_data.columns
Column_Name

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='object')

In [188]:
#d)	Calculate the descriptive statistics of all the variables(integer/float/object etc).

print(Netflix_data.describe(include="all").head())

       show_id   type   title       director                cast  \
count     8780   8780    8780           6150                7956
unique    8780      2    8780           4516                7671
top      s8807  Movie  Zubaan  Rajiv Chilaka  David Attenborough
freq         1   6110       1             19                  19
mean       NaN    NaN     NaN            NaN                 NaN

              country       date_added  release_year rating  duration  \
count            7952             8770   8780.000000   8776      8780
unique            745             1765           NaN     14       220
top     United States  January 1, 2020           NaN  TV-MA  1 Season
freq             2809              108           NaN   3198      1788
mean              NaN              NaN   2014.178474    NaN       NaN

                           listed_in
count                           8780
unique                           514
top     Dramas, International Movies
freq                             361
mean                             NaN

In [189]:
#e)	Check the number of unique values for each column.
Unique_Values=Netflix_data.nunique()
print(Unique_Values)

show_id         8780
type               2
title           8780
director        4516
cast            7671
country          745
date_added      1765
release_year      74
rating            14
duration         220
listed_in        514
dtype: int64

In [190]:
#f)	Check the percentage of missing values for each column
No_of_entries=Netflix_data.notna().sum()
Total_rows=Netflix_data.shape[0]

percentage_of_missing_values=((Total_rows-No_of_entries)/Total_rows)*100
print(percentage_of_missing_values)

show_id          0.000000
type             0.000000
title            0.000000
director        29.954442
cast             9.384966
country          9.430524
date_added       0.113895
release_year     0.000000
rating           0.045558
duration         0.000000
listed_in        0.000000
dtype: float64

In [191]:
#g)	Delete all the rows where Director column has missing values.
Netflix_data.replace([" ",""],np.nan,inplace=True)

DroppedNAN=Netflix_data.dropna(axis=0,subset=["director"])
print(DroppedNAN.count(axis=0))
print(Netflix_data.count(axis=0))

show_id         6150
type            6150
title           6150
director        6150
cast            5678
country         5729
date_added      6150
release_year    6150
rating          6149
duration        6150
listed_in       6150
dtype: int64
show_id         8780
type            8780
title           8780
director        6150
cast            7956
country         7952
date_added      8770
release_year    8780
rating          8776
duration        8780
listed_in       8780
dtype: int64

In [192]:
#h)	Print all the records where country has Germany value (including West Germany). If any other country is there along with Germany, then that row should also come in output.
Germany_Records=Netflix_data[Netflix_data["country"].str.contains("germany|west germany",case=False,na=False)]
print(Germany_Records)

     show_id   type                                title  \
7         s8  Movie                              Sankofa
12       s13  Movie                         Je Suis Karl
129     s130  Movie                   An Unfinished Life
142     s143  Movie                      Freedom Writers
172     s173  Movie                       School of Rock
...      ...    ...                                  ...
8590   s8618  Movie                                Trash
8634   s8662  Movie                      Unfinished Song
8641   s8669  Movie                       V for Vendetta
8702   s8730  Movie                   Where the Money Is
8718   s8746  Movie  Willy Wonka & the Chocolate Factory

                  director                                               cast  \
7             Haile Gerima  Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
12     Christian Schwochow  Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel,...
129       Lasse HallstrÃ¶m  Robert Redford, Jennifer Lopez, Morgan Freeman...
142    Richard LaGravenese  Hilary Swank, Patrick Dempsey, Scott Glenn, Im...
172      Richard Linklater  Jack Black, Joan Cusack, Mike White, Sarah Sil...
...                    ...                                                ...
8590        Stephen Daldry  Wagner Moura, Martin Sheen, Rooney Mara, Selto...
8634  Paul Andrew Williams  Terence Stamp, Gemma Arterton, Christopher Ecc...
8641        James McTeigue  Natalie Portman, Hugo Weaving, Stephen Rea, St...
8702       Marek Kanievska  Paul Newman, Linda Fiorentino, Dermot Mulroney...
8718            Mel Stuart  Gene Wilder, Jack Albertson, Peter Ostrum, Roy...

                                                country          date_added  \
7     United States, Ghana, Burkina Faso, United Kin...  September 24, 2021
12                              Germany, Czech Republic  September 23, 2021
129                              Germany, United States   September 1, 2021
142                              Germany, United States   September 1, 2021
172                              United States, Germany   September 1, 2021
...                                                 ...                 ...
8590                    United Kingdom, Brazil, Germany     January 1, 2019
8634                            United Kingdom, Germany       July 22, 2019
8641             United States, United Kingdom, Germany     October 1, 2018
8702     Germany, United States, United Kingdom, Canada    January 15, 2020
8718          United States, East Germany, West Germany     January 1, 2020

      release_year rating duration  \
7             1993  TV-MA  125 min
12            2021  TV-MA  127 min
129           2005  PG-13  108 min
142           2007  PG-13  124 min
172           2003  PG-13  110 min
...            ...    ...      ...
8590          2014      R  114 min
8634          2012  PG-13   94 min
8641          2005      R  132 min
8702          2000  PG-13   89 min
8718          1971      G  100 min

                                              listed_in
7      Dramas, Independent Movies, International Movies
12                         Dramas, International Movies
129                                              Dramas
142                                              Dramas
172                          Comedies, Music & Musicals
...                                                 ...
8590              Dramas, Independent Movies, Thrillers
8634               Comedies, Dramas, Independent Movies
8641       Action & Adventure, Dramas, Sci-Fi & Fantasy
8702               Action & Adventure, Comedies, Dramas
8718  Children & Family Movies, Classic Movies, Come...

[231 rows x 11 columns]

In [193]:
#i)	Expand Duration column into 2 separate columns – First column having the numeric value and other having String. Eg: 3 seasons should be split in 2 columns having 3 in 1st column and seasons in 2nd column.
Netflix_data[["Duration_No", "Duration_String"]] = Netflix_data["duration"].apply(lambda x: pd.Series(str(x).split(" ", 1)) if pd.notna(x) else pd.Series([np.nan,np.nan]))
print(Netflix_data.sample())

     show_id     type                      title director  \
3168   s3174  TV Show  Teasing Master Takagi-san      NaN

                                                   cast country  \
3168  Rie Takahashi, Yuki Kaji, Konomi Kohara, Mãƒ»A...   Japan

            date_added  release_year rating  duration  \
3168  December 6, 2019          2019  TV-PG  1 Season

                                              listed_in Duration_No  \
3168  Anime Series, International TV Shows, Romantic...           1

     Duration_String
3168          Season

In [194]:
#j)	Split Date added into 3 separate columns having date value in 1st column, month value in 2nd column and year value in 3rd.

Netflix_data["date_added"]=pd.to_datetime(Netflix_data["date_added"],format="mixed")

Netflix_data["day"] = Netflix_data["date_added"].dt.day
Netflix_data["month"] = Netflix_data["date_added"].dt.month_name()
Netflix_data["year"] = Netflix_data["date_added"].dt.year

print(Netflix_data.head(1))

  show_id   type                 title         director cast        country  \
0      s1  Movie  Dick Johnson Is Dead  Kirsten Johnson  NaN  United States

  date_added  release_year rating duration      listed_in Duration_No  \
0 2021-09-25          2020  PG-13   90 min  Documentaries          90

  Duration_String   day      month    year
0             min  25.0  September  2021.0

In [195]:
#k)	Print the number of TV shows/Movies released in each year
print(Netflix_data.groupby(["year","type"]).size())

year    type
2008.0  Movie         1
        TV Show       1
2009.0  Movie         2
2010.0  Movie         1
2011.0  Movie        13
2012.0  Movie         3
2013.0  Movie         6
        TV Show       5
2014.0  Movie        19
        TV Show       5
2015.0  Movie        56
        TV Show      26
2016.0  Movie       250
        TV Show     176
2017.0  Movie       835
        TV Show     348
2018.0  Movie      1234
        TV Show     411
2019.0  Movie      1418
        TV Show     589
2020.0  Movie      1281
        TV Show     594
2021.0  Movie       991
        TV Show     505
dtype: int64

In [196]:
#l)	Rename the column title with movie_title.
Netflix_data.rename(columns={"title":"movie_title"},inplace=True)
print(Netflix_data.head(5))

  show_id     type            movie_title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

  date_added  release_year rating   duration  \
0 2021-09-25          2020  PG-13     90 min
1 2021-09-24          2021  TV-MA  2 Seasons
2 2021-09-24          2021  TV-MA   1 Season
3 2021-09-24          2021  TV-MA   1 Season
4 2021-09-24          2021  TV-MA  2 Seasons

                                           listed_in Duration_No  \
0                                      Documentaries          90
1    International TV Shows, TV Dramas, TV Mysteries           2
2  Crime TV Shows, International TV Shows, TV Act...           1
3                             Docuseries, Reality TV           1
4  International TV Shows, Romantic TV Shows, TV ...           2

  Duration_String   day      month    year
0             min  25.0  September  2021.0
1         Seasons  24.0  September  2021.0
2          Season  24.0  September  2021.0
3          Season  24.0  September  2021.0
4         Seasons  24.0  September  2021.0

In [197]:
#m)	Split Listed_in column into 3 different columns with col name (Genre1, Genre2, Genre3). Split the column based on comma.
Netflix_data[["Genre1","Genre2","Genre3"]]=Netflix_data["listed_in"].str.split(",",expand=True)
print(Netflix_data.head())

  show_id     type            movie_title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

  date_added  release_year rating   duration  \
0 2021-09-25          2020  PG-13     90 min
1 2021-09-24          2021  TV-MA  2 Seasons
2 2021-09-24          2021  TV-MA   1 Season
3 2021-09-24          2021  TV-MA   1 Season
4 2021-09-24          2021  TV-MA  2 Seasons

                                           listed_in Duration_No  \
0                                      Documentaries          90
1    International TV Shows, TV Dramas, TV Mysteries           2
2  Crime TV Shows, International TV Shows, TV Act...           1
3                             Docuseries, Reality TV           1
4  International TV Shows, Romantic TV Shows, TV ...           2

  Duration_String   day      month    year                  Genre1  \
0             min  25.0  September  2021.0           Documentaries
1         Seasons  24.0  September  2021.0  International TV Shows
2          Season  24.0  September  2021.0          Crime TV Shows
3          Season  24.0  September  2021.0              Docuseries
4         Seasons  24.0  September  2021.0  International TV Shows

                    Genre2                  Genre3
0                     None                    None
1                TV Dramas            TV Mysteries
2   International TV Shows   TV Action & Adventure
3               Reality TV                    None
4        Romantic TV Shows             TV Comedies

# Q2.	Import both the attached files (student.csv and marks.csv) in Jupyter notebook and perform following operations:

In [198]:
import pandas as pd
!ls

 Marks.xlsm   sample_data   Student.xlsm   test.csv  'Worksheet in Assignment.xlsm'

In [199]:
marks=pd.read_excel("Marks.xlsm")

print(marks.head())

   Student_id  Mark     City
0           1    95  Chennai
1           2    70    Delhi
2           3    98   Mumbai
3           4    75     Pune
4           5    89    Kochi

In [200]:
Student=pd.read_excel("Student.xlsm")

print(Student.head())

   Student_id  Age  Gender      Grade Employed
0           1   19    Male  1st Class      yes
1           2   20  Female  2nd Class       no
2           3   18    Male  1st Class       no
3           4   21  Female  2nd Class       no
4           5   19    Male  1st Class       no

In [201]:
#Combine both the dataframes into single dataframe which will have all the records from both the tables.

Student_info=pd.merge(Student,marks,on="Student_id",how="outer")
print(Student_info.head())

   Student_id  Age  Gender      Grade Employed  Mark     City
0           1   19    Male  1st Class      yes  95.0  Chennai
1           2   20  Female  2nd Class       no  70.0    Delhi
2           3   18    Male  1st Class       no  98.0   Mumbai
3           4   21  Female  2nd Class       no  75.0     Pune
4           5   19    Male  1st Class       no  89.0    Kochi

In [202]:
#b)	Print the maximum and minimum marks Gender wise.
Genderwise_max_Mark=Student_info.groupby("Gender")["Mark"].max()
Genderwise_min_Mark=Student_info.groupby("Gender")["Mark"].min()
print(Genderwise_max_Mark)
print(Genderwise_min_Mark)

Gender
Female     99.0
Male      100.0
Name: Mark, dtype: float64
Gender
Female    40.0
Male      40.0
Name: Mark, dtype: float64

In [203]:
#c)	Print all the students IDs and their marks who have scored more than the average marks of the class.

x=marks[marks["Mark"]>marks["Mark"].mean()]
print("    Mean Marks",marks["Mark"].mean().round(2),"\n")
print(x)

    Mean Marks 71.39

     Student_id  Mark     City
0             1    95  Chennai
2             3    98   Mumbai
3             4    75     Pune
4             5    89    Kochi
9            12    90    Kochi
..          ...   ...      ...
218         222    74    Kochi
219         223    79  Gwalior
221         225    72  Chennai
224         228    99     Pune
227         231    97   Mumbai

[137 rows x 3 columns]

In [204]:
#d)	Print the dataframe who are Males and are Employed.
x=Student_info[(Student_info["Gender"].str.lower()=="male") & (Student_info["Employed"].str.lower()=="yes")]
print(x.head(5))

    Student_id  Age Gender      Grade Employed  Mark     City
0            1   19   Male  1st Class      yes  95.0  Chennai
5            6   20   Male  2nd Class      yes  69.0  Gwalior
7            8   21   Male  3rd Class      yes  54.0  Chennai
12          13   19   Male  1st Class      yes  92.0  Gwalior
14          15   19   Male  1st Class      yes  97.0     Pune

In [205]:
pd.unique(Student_info["Employed"])#Only two unique values in employed

array(['yes', 'no'], dtype=object)

In [206]:
#e)	Create a new Column ‘IQ_level’ which will have 3 values (Intelligent, Mediocre, weak). If student scored than 80 then Tag him as Intelligent, if student scored between 50-80, then Mediocre, else weak.

def scores(score):
  if score > 80:
    return "Intelligent"
  elif score in range(50,81):
    return "Mediocre"
  else :
    return "Weak"

Student_info["IQ_Level"]=Student_info["Mark"].apply(scores)

print(Student_info.sample(5))

     Student_id  Age  Gender      Grade Employed  Mark     City     IQ_Level
194         195   20  Female  3rd Class      yes  43.0    Delhi         Weak
154         155   21    Male  1st Class       no  89.0  Chennai  Intelligent
111         112   21  Female  1st Class       no  97.0     Pune  Intelligent
144         145   20    Male  3rd Class       no  43.0    Delhi         Weak
196         197   21  Female  2nd Class      yes  74.0     Pune     Mediocre

In [207]:
#f)	Count the number of males and females from each city.

x=Student_info.groupby("City")["Gender"].value_counts()
print(x)

City     Gender
Bhopal   Male      15
         Female    13
Chennai  Male      18
         Female    15
Delhi    Male      20
         Female    12
Gwalior  Male      18
         Female    14
Kochi    Male      21
         Female    10
Mumbai   Female    16
         Male      16
Pune     Male      26
         Female    15
Name: count, dtype: int64

In [208]:
#g)	Print the top 5 Male scorers.
Male_students=Student_info[(Student_info["Gender"].str.lower()=="male")]
Top_5_male=Male_students.sort_values("Mark",ascending=False).head(5)
print(Top_5_male[["Student_id","Gender","Mark"]])

     Student_id Gender   Mark
149         150   Male  100.0
147         148   Male   99.0
145         146   Male   98.0
101         102   Male   98.0
2             3   Male   98.0

In [209]:
#h)	Replace the Male value with M and Female value with F and export this dataframe to excel file in D: (D drive) and name the file as test.csv.
Student_info["Gender"].str.lower().replace(["male","female"],["M","F"],inplace=True)

Student_info.to_csv("test.csv",index=False)

In [210]:
#i)	Check if any student_ID is duplicated.
Student_info["Student_id"].duplicated().sum()

0

In [211]:
#j)	Create a separate dataframe which will have all the Integer/Float variables.
Int_Float_df=Student_info.select_dtypes(include=["Float64","float64","int64",])
Int_Float_df

     Student_id  Age  Mark
0             1   19  95.0
1             2   20  70.0
2             3   18  98.0
3             4   21  75.0
4             5   19  89.0
..          ...  ...   ...
227         228   21  99.0
228         229   20  70.0
229         230   20  55.0
230         231   19  97.0
231         232   20  59.0

[232 rows x 3 columns]

In [214]:
#k)	Get those Student_IDs which are present in Students table but not in Marks table.


#method 1
#Student_IDs=pd.merge(Student,marks,how="inner",on="Student_id")["Student_id"]
#Student_IDs

#method 2
Student_IDs=Student_info[~Student_info["Student_id"].isin(marks["Student_id"])]["Student_id"]
Student_IDs

8      9
9     10
48    49
Name: Student_id, dtype: int64

In [ ]:
'''3.	Explain the concept of missing values. How can you identify the missing values in a Pandas DataFrame ?
What are the different ways of treating/Imputing/Deleting the missing values.
Explain with example.'''

'''Ans. Missing values are the values that were not recorded or not entered in the data frame
when the data is imported in pandas it leads to creation of Nan or None values at the missing value loacations,
NaN for intger/float while None is for object type data.

To identify missing values in NaN/None we us df.isna() or df.isnull() function along with .sum() to count the number of
find number of missing values in the data frame.isna() and isnull() function returns True for missing values and False for
for non-missing values.To get the overview of the data we can use df.info(),it returns summary of the data frame along with
on_null value count.

Treating null values:

1.Deleting NaN values:
  a.drop(axis=0)-->drops rows containg missing values
  b.drop(axis=1)-->drops columns containing missing values
  c.drop()-->drops missing values

2.Imputting Values: Imputation refers to filling in missing values with a
  specific value, mean, median, mode, or even predictions from a machine learning model.
  Function: a)fillna() function is used to fill missing value
            instead of constand value aggregation can be done(such as medium,mean etc.)
            b)ffill() and bfill() can be used to replace the missing value with next observation
            or last observation.

Eg.

In [1]:
import pandas as pd
import numpy as np

# Example DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', np.nan],
        'Age': [25, 30, np.nan, 22],
        'Gender': ['Female', np.nan, 'Male', 'Male']}
df = pd.DataFrame(data)

# Identify missing values
print("Missing values:")
print(df.isna().sum())

# 1. Drop rows with missing values
df_dropped = df.dropna()

# 2. Fill missing values with the mean for 'Age' and mode for 'Gender'
df_filled = df.copy()
df_filled['Age'] = df_filled['Age'].fillna(df_filled['Age'].mean())
df_filled['Gender'] = df_filled['Gender'].fillna(df_filled['Gender'].mode()[0])

# 3. Forward fill for missing values in 'Gender'
df_filled_ffill = df.fillna(method='ffill')


print("\nAfter dropping missing values:")
print(df_dropped)

print("\nAfter filling missing values with mean for 'Age' and mode for 'Gender':")
print(df_filled)

print("\nAfter forward filling missing values:")
print(df_filled_ffill)

Missing values:
Name      1
Age       1
Gender    1
dtype: int64

After dropping missing values:
    Name   Age  Gender
0  Alice  25.0  Female

After filling missing values with mean for 'Age' and mode for 'Gender':
      Name        Age  Gender
0    Alice  25.000000  Female
1      Bob  30.000000    Male
2  Charlie  25.666667    Male
3      NaN  22.000000    Male

After forward filling missing values:
      Name   Age  Gender
0    Alice  25.0  Female
1      Bob  30.0  Female
2  Charlie  30.0    Male
3  Charlie  22.0    Male

<ipython-input-1-83269337a782>:23: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_filled_ffill = df.fillna(method='ffill')