In [25]:
import os
import numpy as np
import pandas as pd

# 1.	Import the attached Netflix csv file in Jupyter notebook and perform following operations using Pandas:

In [33]:
Data = pd.read_excel('netflix_title.xlsx')
Data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV"
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."
...,...,...,...,...,...,...,...,...,...,...,...
8775,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers"
8776,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies"
8777,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies"
8778,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies"
8779,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals"

## a)	Print the first 5 rows and last 5 rows of the dataframe

In [34]:
print(Data.head())
print(Data.tail())

  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season
3  September 24, 2021          2021  TV-MA   1 Season
4  September 24, 2021          2021  TV-MA  2 Seasons

                                           listed_in
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...
     show_id     type        title         director  \
8775   s8803    Movie       Zodiac    David Fincher
8776   s8804  TV Show  Zombie Dumb              NaN
8777   s8805    Movie   Zombieland  Ruben Fleischer
8778   s8806    Movie         Zoom     Peter Hewitt
8779   s8807    Movie       Zubaan      Mozez Singh

                                                   cast        country  \
8775  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8776                                                NaN            NaN
8777  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8778  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8779  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

             date_added  release_year rating   duration  \
8775  November 20, 2019          2007      R    158 min
8776       July 1, 2019          2018  TV-Y7  2 Seasons
8777   November 1, 2019          2009      R     88 min
8778   January 11, 2020          2006     PG     88 min
8779      March 2, 2019          2015  TV-14    111 min

                                           listed_in
8775                  Cult Movies, Dramas, Thrillers
8776          Kids' TV, Korean TV Shows, TV Comedies
8777                         Comedies, Horror Movies
8778              Children & Family Movies, Comedies
8779  Dramas, International Movies, Music & Musicals

## b)	Check how many rows and columns are there using Pandas function.

In [35]:
print(f'Number of rows: {df.shape[0]}')
print(f'Number of columns: {df.shape[1]}')

Number of rows: 8780
Number of columns: 11

## c)	Print all the column names.

In [36]:
print(Data.columns)

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='object')

## d)	Calculate the descriptive statistics of all the variables(integer/float/object etc).

In [37]:
print(Data.describe(include='all'))

       show_id   type                 title       director  \
count     8780   8780                  8780           6150
unique    8780      2                  8780           4516
top         s1  Movie  Dick Johnson Is Dead  Rajiv Chilaka
freq         1   6110                     1             19
mean       NaN    NaN                   NaN            NaN
std        NaN    NaN                   NaN            NaN
min        NaN    NaN                   NaN            NaN
25%        NaN    NaN                   NaN            NaN
50%        NaN    NaN                   NaN            NaN
75%        NaN    NaN                   NaN            NaN
max        NaN    NaN                   NaN            NaN

                      cast        country       date_added  release_year  \
count                 7956           7952             8770   8780.000000
unique                7671            745             1765           NaN
top     David Attenborough  United States  January 1, 2020           NaN
freq                    19           2809              108           NaN
mean                   NaN            NaN              NaN   2014.178474
std                    NaN            NaN              NaN      8.827938
min                    NaN            NaN              NaN   1925.000000
25%                    NaN            NaN              NaN   2013.000000
50%                    NaN            NaN              NaN   2017.000000
75%                    NaN            NaN              NaN   2019.000000
max                    NaN            NaN              NaN   2021.000000

       rating  duration                     listed_in
count    8776      8780                          8780
unique     14       220                           514
top     TV-MA  1 Season  Dramas, International Movies
freq     3198      1788                           361
mean      NaN       NaN                           NaN
std       NaN       NaN                           NaN
min       NaN       NaN                           NaN
25%       NaN       NaN                           NaN
50%       NaN       NaN                           NaN
75%       NaN       NaN                           NaN
max       NaN       NaN                           NaN

## e)	Check the number of unique values for each column.

In [38]:
print(Data.nunique())

show_id         8780
type               2
title           8780
director        4516
cast            7671
country          745
date_added      1765
release_year      74
rating            14
duration         220
listed_in        514
dtype: int64

## f)	Check the percentage of missing values for each column.

In [39]:
missing_percentage = (Data.isna().sum() / len(df)) * 100
print(missing_percentage)

show_id          0.000000
type             0.000000
title            0.000000
director        29.954442
cast             9.384966
country          9.430524
date_added       0.113895
release_year     0.000000
rating           0.045558
duration         0.000000
listed_in        0.000000
dtype: float64

## g)	Delete all the rows where Director column has missing values.

In [44]:
Data_cleaned = df.dropna(subset=['director'])
print(Data_cleaned)

     show_id     type                             title  \
0         s1    Movie              Dick Johnson Is Dead
2         s3  TV Show                         Ganglands
5         s6  TV Show                     Midnight Mass
6         s7    Movie  My Little Pony: A New Generation
7         s8    Movie                           Sankofa
...      ...      ...                               ...
8774   s8802    Movie                           Zinzana
8775   s8803    Movie                            Zodiac
8777   s8805    Movie                        Zombieland
8778   s8806    Movie                              Zoom
8779   s8807    Movie                            Zubaan

                            director  \
0                    Kirsten Johnson
2                    Julien Leclercq
5                      Mike Flanagan
6     Robert Cullen, JosÃ© Luis Ucha
7                       Haile Gerima
...                              ...
8774                 Majid Al Ansari
8775                   David Fincher
8777                 Ruben Fleischer
8778                    Peter Hewitt
8779                     Mozez Singh

                                                   cast  \
0                                                   NaN
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
5     Kate Siegel, Zach Gilford, Hamish Linklater, H...
6     Vanessa Hudgens, Kimiko Glenn, James Marsden, ...
7     Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
...                                                 ...
8774  Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...
8775  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...
8777  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...
8778  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...
8779  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...

                                                country          date_added  \
0                                         United States  September 25, 2021
2                                                   NaN  September 24, 2021
5                                                   NaN  September 24, 2021
6                                                   NaN  September 24, 2021
7     United States, Ghana, Burkina Faso, United Kin...  September 24, 2021
...                                                 ...                 ...
8774                       United Arab Emirates, Jordan       March 9, 2016
8775                                      United States   November 20, 2019
8777                                      United States    November 1, 2019
8778                                      United States    January 11, 2020
8779                                              India       March 2, 2019

      release_year rating  duration  \
0             2020  PG-13    90 min
2             2021  TV-MA  1 Season
5             2021  TV-MA  1 Season
6             2021     PG    91 min
7             1993  TV-MA   125 min
...            ...    ...       ...
8774          2015  TV-MA    96 min
8775          2007      R   158 min
8777          2009      R    88 min
8778          2006     PG    88 min
8779          2015  TV-14   111 min

                                              listed_in
0                                         Documentaries
2     Crime TV Shows, International TV Shows, TV Act...
5                    TV Dramas, TV Horror, TV Mysteries
6                              Children & Family Movies
7      Dramas, Independent Movies, International Movies
...                                                 ...
8774            Dramas, International Movies, Thrillers
8775                     Cult Movies, Dramas, Thrillers
8777                            Comedies, Horror Movies
8778                 Children & Family Movies, Comedies
8779     Dramas, International Movies, Music & Musicals

[6150 rows x 11 columns]

## h)	Print all the records where country has Germany value (including West Germany). If any other country is there along with Germany, then that row should also come in output.

In [48]:
germany_rows = df[df['country'].str.contains('Germany', case=False, na=False)]
print(germany_rows)

     show_id   type                                title  \
7         s8  Movie                              Sankofa
12       s13  Movie                         Je Suis Karl
129     s130  Movie                   An Unfinished Life
142     s143  Movie                      Freedom Writers
172     s173  Movie                       School of Rock
...      ...    ...                                  ...
8590   s8618  Movie                                Trash
8634   s8662  Movie                      Unfinished Song
8641   s8669  Movie                       V for Vendetta
8702   s8730  Movie                   Where the Money Is
8718   s8746  Movie  Willy Wonka & the Chocolate Factory

                  director                                               cast  \
7             Haile Gerima  Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
12     Christian Schwochow  Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel,...
129       Lasse HallstrÃ¶m  Robert Redford, Jennifer Lopez, Morgan Freeman...
142    Richard LaGravenese  Hilary Swank, Patrick Dempsey, Scott Glenn, Im...
172      Richard Linklater  Jack Black, Joan Cusack, Mike White, Sarah Sil...
...                    ...                                                ...
8590        Stephen Daldry  Wagner Moura, Martin Sheen, Rooney Mara, Selto...
8634  Paul Andrew Williams  Terence Stamp, Gemma Arterton, Christopher Ecc...
8641        James McTeigue  Natalie Portman, Hugo Weaving, Stephen Rea, St...
8702       Marek Kanievska  Paul Newman, Linda Fiorentino, Dermot Mulroney...
8718            Mel Stuart  Gene Wilder, Jack Albertson, Peter Ostrum, Roy...

                                                country          date_added  \
7     United States, Ghana, Burkina Faso, United Kin...  September 24, 2021
12                              Germany, Czech Republic  September 23, 2021
129                              Germany, United States   September 1, 2021
142                              Germany, United States   September 1, 2021
172                              United States, Germany   September 1, 2021
...                                                 ...                 ...
8590                    United Kingdom, Brazil, Germany     January 1, 2019
8634                            United Kingdom, Germany       July 22, 2019
8641             United States, United Kingdom, Germany     October 1, 2018
8702     Germany, United States, United Kingdom, Canada    January 15, 2020
8718          United States, East Germany, West Germany     January 1, 2020

      release_year rating duration  \
7             1993  TV-MA  125 min
12            2021  TV-MA  127 min
129           2005  PG-13  108 min
142           2007  PG-13  124 min
172           2003  PG-13  110 min
...            ...    ...      ...
8590          2014      R  114 min
8634          2012  PG-13   94 min
8641          2005      R  132 min
8702          2000  PG-13   89 min
8718          1971      G  100 min

                                              listed_in
7      Dramas, Independent Movies, International Movies
12                         Dramas, International Movies
129                                              Dramas
142                                              Dramas
172                          Comedies, Music & Musicals
...                                                 ...
8590              Dramas, Independent Movies, Thrillers
8634               Comedies, Dramas, Independent Movies
8641       Action & Adventure, Dramas, Sci-Fi & Fantasy
8702               Action & Adventure, Comedies, Dramas
8718  Children & Family Movies, Classic Movies, Come...

[231 rows x 11 columns]

## i)	Expand Duration column into 2 separate columns – First column having the numeric value and other having String. Eg: 3 seasons should be split in 2 columns having 3 in 1st column and seasons in 2nd column.

In [58]:
df[['duration_Value', 'duration_Type']] = df['duration'].str.split(' ', expand=True)
df['duration_Value'] = df['duration_Value'].astype(int) 
df[['duration_Value', 'duration_Type']]

      duration_Value duration_Type
0                 90           min
1                  2       Seasons
2                  1        Season
3                  1        Season
4                  2       Seasons
...              ...           ...
8775             158           min
8776               2       Seasons
8777              88           min
8778              88           min
8779             111           min

[8780 rows x 2 columns]

## j)	Split Date added into 3 separate columns having date value in 1st column, month value in 2nd column and year value in 3rd.

In [84]:
df[['Month', 'Day', 'Year', 'none']] = df['date_added'].str.split(' ', expand=True)
print(df[['date_added', 'Month', 'Year']].head())

           date_added      Month  Year
0  September 25, 2021  September  2021
1  September 24, 2021  September  2021
2  September 24, 2021  September  2021
3  September 24, 2021  September  2021
4  September 24, 2021  September  2021

## k)	Print the number of TV shows/Movies released in each year.

In [85]:
release_count = df['release_year'].value_counts().sort_index()
print(release_count)

release_year
1925       1
1942       2
1943       3
1944       3
1945       4
        ...
2017    1030
2018    1141
2019    1024
2020     952
2021     592
Name: count, Length: 74, dtype: int64

## l)	Rename the column title with movie_title.

In [86]:
df.rename(columns={'title': 'movie_title'}, inplace=True)
print(df.columns)

Index(['show_id', 'type', 'movie_title', 'director', 'cast', 'country',
       'date_added', 'release_year', 'rating', 'duration', 'listed_in',
       'duration_Value', 'duration_Type', 'Date', 'Month', 'Year', 'None',
       'Date_added_day', 'Date_added_month', 'Date_added_year', 'none', 'Day'],
      dtype='object')

## m)	Split Listed_in column into 3 different columns with col name (Genre1, Genre2, Genre3). Split the column based on comma.

In [87]:
df[['Genre1', 'Genre2', 'Genre3']] = df['listed_in'].str.split(',', expand=True, n=2)
print(df[['listed_in', 'Genre1', 'Genre2', 'Genre3']].head())

                                           listed_in                  Genre1  \
0                                      Documentaries           Documentaries
1    International TV Shows, TV Dramas, TV Mysteries  International TV Shows
2  Crime TV Shows, International TV Shows, TV Act...          Crime TV Shows
3                             Docuseries, Reality TV              Docuseries
4  International TV Shows, Romantic TV Shows, TV ...  International TV Shows

                    Genre2                  Genre3
0                     None                    None
1                TV Dramas            TV Mysteries
2   International TV Shows   TV Action & Adventure
3               Reality TV                    None
4        Romantic TV Shows             TV Comedies

# 2.	Import both the attached files (student.csv and marks.csv) in Jupyter notebook and perform following operations:

In [125]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'Assigment_Python_Basics.docx', 'Assignment Pandas.pdf', 'Assignment submission', 'Assignment.docx', 'marks.xlsm', 'Mini projects', 'netflix_title.xlsx', 'Numpy assignment.ipynb', 'Pandas Assignment (1)', 'Pandas Assignment (1).zip', 'Student Performance Analysis (1).docx', 'students.xlsm', 'test.csv', 'Untitled.ipynb']

In [102]:
students = pd.read_excel('students.xlsm')
marks = pd.read_excel('marks.xlsm')
print(students)
print(marks)

     Student_id  Age  Gender      Grade Employed
0             1   19    Male  1st Class      yes
1             2   20  Female  2nd Class       no
2             3   18    Male  1st Class       no
3             4   21  Female  2nd Class       no
4             5   19    Male  1st Class       no
..          ...  ...     ...        ...      ...
227         228   21  Female  1st Class       no
228         229   20    Male  2nd Class       no
229         230   20    Male  3rd Class      yes
230         231   19  Female  1st Class      yes
231         232   20    Male  3rd Class      yes

[232 rows x 5 columns]
     Student_id  Mark     City
0             1    95  Chennai
1             2    70    Delhi
2             3    98   Mumbai
3             4    75     Pune
4             5    89    Kochi
..          ...   ...      ...
224         228    99     Pune
225         229    70  Chennai
226         230    55    Delhi
227         231    97   Mumbai
228         232    59     Pune

[229 rows x 3 columns]

## a)	Combine both the dataframes into single dataframe which will have all the records from both the tables.

In [109]:
combined_data = pd.merge(students, marks, on='Student_id', how='outer')
print(combined_data)

     Student_id  Age  Gender      Grade Employed  Mark     City
0             1   19    Male  1st Class      yes  95.0  Chennai
1             2   20  Female  2nd Class       no  70.0    Delhi
2             3   18    Male  1st Class       no  98.0   Mumbai
3             4   21  Female  2nd Class       no  75.0     Pune
4             5   19    Male  1st Class       no  89.0    Kochi
..          ...  ...     ...        ...      ...   ...      ...
227         228   21  Female  1st Class       no  99.0     Pune
228         229   20    Male  2nd Class       no  70.0  Chennai
229         230   20    Male  3rd Class      yes  55.0    Delhi
230         231   19  Female  1st Class      yes  97.0   Mumbai
231         232   20    Male  3rd Class      yes  59.0     Pune

[232 rows x 7 columns]

## b)	Print the maximum and minimum marks Gender wise.

In [110]:
gender_marks = combined_data.groupby('Gender')['Mark'].agg(['max', 'min'])
print(gender_marks)

          max   min
Gender
Female   99.0  40.0
Male    100.0  40.0

## c)	Print all the students IDs and their marks who have scored more than the average marks of the class.

In [112]:
average_marks = combined_data['Mark'].mean()
above_avg_students = combined_data[combined_data['Mark'] > average_marks][['Student_id', 'Mark']]
print(above_avg_students)

     Student_id  Mark
0             1  95.0
2             3  98.0
3             4  75.0
4             5  89.0
11           12  90.0
..          ...   ...
221         222  74.0
222         223  79.0
224         225  72.0
227         228  99.0
230         231  97.0

[137 rows x 2 columns]

## d)	Print the dataframe who are Males and are Employed.

In [117]:
males_employed = combined_data[(combined_data['Gender'] == 'Male') & (combined_data['Employed'] == True)]
print(males_employed)

Empty DataFrame
Columns: [Student_id, Age, Gender, Grade, Employed, Mark, City]
Index: []

## e)	Create a new Column ‘IQ_level’ which will have 3 values (Intelligent, Mediocre, weak). If student scored than 80 then Tag him as Intelligent, if student scored between 50-80, then Mediocre, else weak.

In [120]:
def iq_level(score):
    if score > 80:
        return 'Intelligent'
    elif score >= 50:
        return 'Mediocre'
    else:
        return 'Weak'

combined_data['IQ_level'] = combined_data['Mark'].apply(iq_level)
print(combined_data[['Student_id', 'Mark', 'IQ_level']])

     Student_id  Mark     IQ_level
0             1  95.0  Intelligent
1             2  70.0     Mediocre
2             3  98.0  Intelligent
3             4  75.0     Mediocre
4             5  89.0  Intelligent
..          ...   ...          ...
227         228  99.0  Intelligent
228         229  70.0     Mediocre
229         230  55.0     Mediocre
230         231  97.0  Intelligent
231         232  59.0     Mediocre

[232 rows x 3 columns]

## f)	Count the number of males and females from each city.

In [121]:
gender_city_count = combined_data.groupby(['City', 'Gender']).size().unstack(fill_value=0)
print(gender_city_count)

Gender   Female  Male
City
Bhopal       13    15
Chennai      15    18
Delhi        12    20
Gwalior      14    18
Kochi        10    21
Mumbai       16    16
Pune         15    26

## g)	Print the top 5 Male scorers.

In [122]:
top_5_male_scorers = combined_data[combined_data['Gender'] == 'Male'].nlargest(5, 'Mark')
print(top_5_male_scorers[['Student_id', 'Mark']])

     Student_id   Mark
149         150  100.0
147         148   99.0
2             3   98.0
60           61   98.0
62           63   98.0

## h)	Replace the Male value with M and Female value with F and export this dataframe to excel file in D: (D drive) and name the file as test.csv.

In [124]:
combined_df['Gender'] = combined_df['Gender'].replace({'Male': 'M', 'Female': 'F'})
combined_df.to_csv(r'D:/test.csv', index=False)

In [127]:
New = pd.read_csv('test.csv')
New

     Student_id  Age Gender      Grade Employed  Mark     City     IQ_level
0             1   19      M  1st Class      yes  95.0  Chennai  Intelligent
1             2   20      F  2nd Class       no  70.0    Delhi     Mediocre
2             3   18      M  1st Class       no  98.0   Mumbai  Intelligent
3             4   21      F  2nd Class       no  75.0     Pune     Mediocre
4             5   19      M  1st Class       no  89.0    Kochi  Intelligent
..          ...  ...    ...        ...      ...   ...      ...          ...
227         228   21      F  1st Class       no  99.0     Pune  Intelligent
228         229   20      M  2nd Class       no  70.0  Chennai     Mediocre
229         230   20      M  3rd Class      yes  55.0    Delhi     Mediocre
230         231   19      F  1st Class      yes  97.0   Mumbai  Intelligent
231         232   20      M  3rd Class      yes  59.0     Pune     Mediocre

[232 rows x 8 columns]

## i)	Check if any student_ID is duplicated.

In [133]:
duplicate_ids = combined_data['Student_id'].duplicated().sum()
print(f"Number of duplicated Student_IDs: {duplicate_ids}")

Number of duplicated Student_IDs: 0

## j)	Create a separate dataframe which will have all the Integer/Float variables.

In [153]:
numeric_df = combined_data.select_dtypes(include=['int64', 'float64'])
print(numeric_df)

     Student_id  Age  Mark
0             1   19  95.0
1             2   20  70.0
2             3   18  98.0
3             4   21  75.0
4             5   19  89.0
..          ...  ...   ...
227         228   21  99.0
228         229   20  70.0
229         230   20  55.0
230         231   19  97.0
231         232   20  59.0

[232 rows x 3 columns]

## k)	Get those Student_IDs which are present in Students table but not in Marks table.

In [149]:
students_not_in_marks = combined_data[~combined_data['Student_id'].isin(marks['Student_id'])]
print(students_not_in_marks[['Student_id']])

    Student_id
8            9
9           10
48          49

# 3. Explain the concept of missing values. How can you identify the missing values in a Pandas DataFrame ?
# What are the different ways of treating/Imputing/Deleting the missing values.
# Explain with example.

In [163]:
data = {'Name': ['Raghul', 'Rajesh', 'Ram', 'Ravi', 'Raja','Rakshan'],
        'Age': [25, 49, np.nan, np.nan, 37, 22],
        'Marks': [98, 78, 65, np.nan, 52, np.nan]}

df = pd.DataFrame(data)
print(df)

      Name   Age  Marks
0   Raghul  25.0   98.0
1   Rajesh  49.0   78.0
2      Ram   NaN   65.0
3     Ravi   NaN    NaN
4     Raja  37.0   52.0
5  Rakshan  22.0    NaN

### We can identify missing values using the function df.isnull(). It will return boolean dataframe indicating the missing values

In [165]:
print(df.isnull())

    Name    Age  Marks
0  False  False  False
1  False  False  False
2  False   True  False
3  False   True   True
4  False  False  False
5  False  False   True

In [166]:
print(df.isnull().sum())

Name     0
Age      2
Marks    2
dtype: int64

### i. Deleting rows or columns with missing values

In [167]:
df_dropped_rows = df.dropna()
print(df_dropped_rows)

     Name   Age  Marks
0  Raghul  25.0   98.0
1  Rajesh  49.0   78.0
4    Raja  37.0   52.0

In [168]:
df_dropped_cols = df.dropna(axis=1)
print(df_dropped_cols)

      Name
0   Raghul
1   Rajesh
2      Ram
3     Ravi
4     Raja
5  Rakshan

### ii. We can imputate by filling real values.

In [169]:
df_filled = df.fillna(20)  # Filling a fixed value of 20 instead of missing values
print(df_filled)

      Name   Age  Marks
0   Raghul  25.0   98.0
1   Rajesh  49.0   78.0
2      Ram  20.0   65.0
3     Ravi  20.0   20.0
4     Raja  37.0   52.0
5  Rakshan  22.0   20.0